// c = index poprawnej odpowiedzi
export const QUESTIONS = [
  { q: 'Która planeta jest najbliżej Słońca?', a: ['Wenus', 'Merkury', 'Mars', 'Ziemia'], c: 1 },
  { q: 'Ile kontynentów jest na Ziemi?', a: ['5', '6', '7', '8'], c: 2 },
  { q: 'Stolica Australii to…', a: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], c: 2 },
  { q: 'Symbol chemiczny złota to…', a: ['Ag', 'Au', 'Go', 'Fe'], c: 1 },
  { q: 'Ile boków ma dwunastokąt?', a: ['10', '11', '12', '20'], c: 2 },
  { q: 'Kto namalował „Mona Lisę”?', a: ['Michał Anioł', 'Rafael', 'Leonardo da Vinci', 'Donatello'], c: 2 },
  { q: 'Najdłuższa rzeka Polski to…', a: ['Odra', 'Warta', 'Wisła', 'Bug'], c: 2 },
  { q: 'Ile minut trwa mecz piłki nożnej (bez doliczonego)?', a: ['60', '80', '90', '100'], c: 2 },
  { q: 'Największy ocean świata to…', a: ['Atlantycki', 'Indyjski', 'Spokojny', 'Arktyczny'], c: 2 },
  { q: 'Który pierwiastek ma symbol „O”?', a: ['Ołów', 'Tlen', 'Osm', 'Złoto'], c: 1 },
  { q: 'W którym roku upadł mur berliński?', a: ['1987', '1989', '1991', '1993'], c: 1 },
  { q: 'Ile strun ma standardowa gitara?', a: ['4', '5', '6', '7'], c: 2 },
  { q: 'Jak nazywa się największa pustynia świata?', a: ['Sahara', 'Gobi', 'Antarktyda', 'Kalahari'], c: 2 },
  { q: 'Który kraj wynalazł pizzę?', a: ['Grecja', 'Włochy', 'Hiszpania', 'Francja'], c: 1 },
  { q: 'Ile kości ma dorosły człowiek?', a: ['186', '206', '226', '246'], c: 1 },
  { q: 'Stolica Japonii to…', a: ['Osaka', 'Kioto', 'Tokio', 'Nagoja'], c: 2 },
  { q: 'Jaki jest największy ssak na świecie?', a: ['Słoń afrykański', 'Płetwal błękitny', 'Kaszalot', 'Żyrafa'], c: 1 },
  { q: 'Ile wynosi 15% z 200?', a: ['25', '30', '35', '20'], c: 1 },
  { q: 'Kto napisał „Pana Tadeusza”?', a: ['Słowacki', 'Norwid', 'Mickiewicz', 'Sienkiewicz'], c: 2 },
  { q: 'Który gaz stanowi ~78% atmosfery?', a: ['Tlen', 'Azot', 'CO₂', 'Argon'], c: 1 },
  { q: 'Ile stron ma kostka do gry?', a: ['4', '6', '8', '12'], c: 1 },
  { q: 'Najwyższy szczyt świata to…', a: ['K2', 'Mount Everest', 'Kangczendzonga', 'Lhotse'], c: 1 },
  { q: 'Który firma stworzyła Maria?', a: ['Sega', 'Sony', 'Nintendo', 'Atari'], c: 2 },
  { q: 'Ile lat trwa jedna dekada?', a: ['5', '10', '20', '100'], c: 1 },
  { q: 'Jaka waluta obowiązuje w Japonii?', a: ['Won', 'Juan', 'Jen', 'Bat'], c: 2 },
  { q: 'Prędkość światła to około…', a: ['300 tys. km/s', '300 km/s', '3 mln km/s', '30 tys. km/s'], c: 0 },
  { q: 'Ile graczy jest w drużynie siatkówki na boisku?', a: ['5', '6', '7', '11'], c: 1 },
  { q: 'Który kolor powstaje z żółtego i niebieskiego?', a: ['Zielony', 'Pomarańczowy', 'Fioletowy', 'Brązowy'], c: 0 },
  { q: 'Stolica Kanady to…', a: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], c: 2 },
  { q: 'Ile sekund ma godzina?', a: ['360', '3600', '6000', '1440'], c: 1 },
];
